# Generated by Django 5.2.6 on 2025-10-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('series', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
