# Generated by Django 5.2.6 on 2025-10-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='character',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
