# Generated by Django 5.2.6 on 2025-10-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_viewer', '0002_alter_character_options_character_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='in_trade_list',
            field=models.BooleanField(default=False),
        ),
    ]
