# Generated by Django 5.2.6 on 2025-10-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_viewer', '0004_character_user_alter_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='key_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='character',
            name='keys',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='series',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
